spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master/xml

server:
  port: 8080

