version: '1'

services:
  app:
    image: 'rugram:latest'
    build:
      context: .
    container_name: app
    networks:
      - default
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  postgres-db:
    image: 'postgres:14'
    container_name: postgres-db
    ports:
      - 5432:5432
    hostname: postgres-db
    networks:
      - default
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres



